### ISSUE TITLE
Null Pointer Exception saving JS file

### ISSUE THREAD

**Issue by Mardonis** [luka-zitnik/jshint-for-netbeans#2] opened 2015-09-22 17:28 UTC
After making some changes to a js file and then closing the file and clicking save an null pointer exception error came up.

java.lang.NullPointerException
    at lukazitnik.jshint.annotations.EditorRegistryListener.propertyChange(EditorRegistryListener.java:32)
    at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
    at org.netbeans.api.editor.EditorRegistry.fireEvents(EditorRegistry.java:544)
    at org.netbeans.api.editor.EditorRegistry.releasedByCloneableEditor(EditorRegistry.java:338)
    at org.netbeans.api.editor.EditorRegistry$CloneableEditorUsageL.propertyChange(EditorRegistry.java:709)
    at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
    at java.awt.Component.firePropertyChange(Component.java:8422)
    at org.openide.text.QuietEditorPane.firePropertyChange(QuietEditorPane.java:210)
    at javax.swing.JComponent.putClientProperty(JComponent.java:4096)
    at org.openide.text.CloneableEditor.componentClosed(CloneableEditor.java:326)
    at org.netbeans.core.spi.multiview.text.MultiViewCloneableEditor.componentClosed(MultiViewCloneableEditor.java:119)
    at org.netbeans.core.spi.multiview.text.MultiViewEditorElement.componentClosed(MultiViewEditorElement.java:129)
    at org.netbeans.core.multiview.MultiViewPeer.peerComponentClosed(MultiViewPeer.java:329)
    at org.netbeans.core.multiview.MultiViewCloneableTopComponent.componentClosed(MultiViewCloneableTopComponent.java:129)
[catch] at org.openide.windows.WindowManager.componentCloseNotify(WindowManager.java:322)
    at org.netbeans.core.windows.WindowManagerImpl.notifyTopComponentClosed(WindowManagerImpl.java:1156)
    at org.netbeans.core.windows.Central.removeModeTopComponent(Central.java:1025)
    at org.netbeans.core.windows.Central.userClosedTopComponent(Central.java:2037)
    at org.netbeans.core.windows.view.DefaultView.userClosedTopComponent(DefaultView.java:794)
    at org.netbeans.core.windows.view.ui.TabbedHandler.actionPerformed(TabbedHandler.java:337)
    at org.netbeans.core.multitabs.Controller.postActionEvent(Controller.java:133)
    at org.netbeans.core.multitabs.impl.CloseButtonHandler.mouseClicked(CloseButtonHandler.java:96)
    at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
    at java.awt.Component.processMouseEvent(Component.java:6528)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6290)
    at java.awt.Container.processEvent(Container.java:2234)
    at java.awt.Component.dispatchEventImpl(Component.java:4881)
    at java.awt.Container.dispatchEventImpl(Container.java:2292)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4542)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
    at java.awt.Container.dispatchEventImpl(Container.java:2278)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by luka-zitnik** [comment] 2015-09-22 22:41
This is very similar to #1. Fixing it might fix this one too.

**Comment by luka-zitnik** [comment] 2015-10-01 23:13
I've bumped into an exception report at http://statistics.netbeans.org. Can't say if you've made it or not. Thank you anyway. You've been very helpful. The issue is fixed in version 1.1.2 of JSHint for NetBeans.

**Closed as completed by luka-zitnik** 2015-10-01 23:13 UTC
